# GPLab Configuration File - Public Security Reform Experiment

# --- Large Language Model (LLM) and Embedding Model Configuration ---
llm_api_configs:
  - base_url: "http://localhost:3000/v1/"
    api_key: "sk-V395yxePMIyg6eCiNtL2mdlD1LAqA3KKAgj783ElOditm151"
    model: "THUDM/glm-4-9b-chat"
    temperature: 0.7
    top_p: 0.9
    description: "Local GLM-4 for public security simulation"
    weight: 1.0

agent_driver_llm_index: [0]
other_llm_index: [0]
embedding_api_index: [0]

# QPS Control Configuration
max_concurrent_requests: 10

use_local_embedding_model: True
local_embedding_model_path: "C://Users//Cromwell//.cache//huggingface//hub//models--sentence-transformers--all-MiniLM-L6-v2//snapshots//e4ce9877abf3edfe10b0d82785e83bdcb973e22e"
embedding_dimension: 384
embedding_device: "cpu"

# --- Social Agent Configuration ---
agent_data_path: "../data/llm_mock_profiles.json"
agent_sample_size: 100
agent_sample_seed: 654
agent_sampling_method: "random"

# Agent Memory System Configuration
memory_reflection_threshold: 5
memory_reflection_count: 2
memory_time_weight_lambda: 0.8
memory_retrieval_k: 5

# Agent Decision Principles
agent_decision_principles:
  - "Consider your safety concerns, daily routines, and risk tolerance when making decisions about movement and activities."
  - "Evaluate the perceived safety of different areas and times based on available information."
  - "Balance between personal freedom and safety precautions."

# --- Social Subsystem Configuration ---
subsystem_directory_group: "public_security"
active_subsystems:
  - "PublicSafetySystem"
  - "CommunityBehaviorSystem"

# Configuration specific to each subsystem
subsystem_configs:
  PublicSafetySystem:
    required_agent_attributes: [
      "id",
      "basic_info.age",
      "basic_info.gender",
      "basic_info.residence_type"
    ]
    environment_attributes: ["crime_statistics", "patrol_coverage", "safety_measures", "incident_reports"]
    decision_attributes:
      - name: "travel_time_preference"
        description: "<choose from: 'daytime_only', 'avoid_late_night', 'no_restriction'>"
      - name: "area_avoidance"
        description: "<choose from: 'avoid_high_crime_areas', 'cautious_everywhere', 'no_avoidance'>"
      - name: "safety_precautions"
        description: "<choose from: 'high_vigilance', 'moderate_caution', 'normal_behavior'>"
    
    # Security policies by epoch
    security_policies:
      "0": {
        "patrol_density": 0.5,
        "surveillance_coverage": 0.3,
        "community_policing": False,
        "emergency_response_time": 15,
        "neighborhood_watch": False,
        "smart_policing": False
      }
      "1": {
        "patrol_density": 0.5,
        "surveillance_coverage": 0.3,
        "community_policing": False,
        "emergency_response_time": 15,
        "neighborhood_watch": False,
        "smart_policing": False
      }
      "2": {  # Reform begins
        "patrol_density": 0.7,
        "surveillance_coverage": 0.5,
        "community_policing": True,
        "emergency_response_time": 12,
        "neighborhood_watch": True,
        "smart_policing": False
      }
      "3": {
        "patrol_density": 0.8,
        "surveillance_coverage": 0.6,
        "community_policing": True,
        "emergency_response_time": 10,
        "neighborhood_watch": True,
        "smart_policing": False
      }
      "4": {  # Full implementation
        "patrol_density": 0.9,
        "surveillance_coverage": 0.8,
        "community_policing": True,
        "emergency_response_time": 8,
        "neighborhood_watch": True,
        "smart_policing": True
      }
      "5": {
        "patrol_density": 0.9,
        "surveillance_coverage": 0.8,
        "community_policing": True,
        "emergency_response_time": 8,
        "neighborhood_watch": True,
        "smart_policing": True
      }

  CommunityBehaviorSystem:
    required_agent_attributes: ["id", "social_attributes.social_style"]
    environment_attributes: ["community_cohesion", "public_activities", "safety_perception"]
    decision_attributes: []
    
    # Crime model parameters
    base_crime_rate: 0.02

# --- Simulation and Evaluation Configuration ---
simulation_name_prefix: "public_security"
num_epochs: 6
start_date: "2024-01-01"
epoch_duration_days: 30
save_decision_prompts: True

# --- Logging Configuration ---
log_level: "INFO" 