# GPLab Configuration File - Youth Gaming Limit Policy Experiment

# --- Large Language Model (LLM) and Embedding Model Configuration ---
llm_api_configs:
  - base_url: "http://localhost:3000/v1/"
    api_key: "sk-V395yxePMIyg6eCiNtL2mdlD1LAqA3KKAgj783ElOditm151"
    model: "THUDM/glm-4-9b-chat"
    temperature: 0.7
    top_p: 0.9
    description: "Local GLM-4 for youth gaming policy simulation"
    weight: 1.0

agent_driver_llm_index: [0]
other_llm_index: [0]
embedding_api_index: [0]

# QPS Control Configuration
max_concurrent_requests: 10

use_local_embedding_model: True
local_embedding_model_path: "C://Users//Cromwell//.cache//huggingface//hub//models--sentence-transformers--all-MiniLM-L6-v2//snapshots//e4ce9877abf3edfe10b0d82785e83bdcb973e22e"
embedding_dimension: 384
embedding_device: "cpu"

# --- Social Agent Configuration ---
agent_data_path: "../data/llm_mock_profiles.json"
agent_sample_size: 100
agent_sample_seed: 246
agent_sampling_method: "random"

# Agent Memory System Configuration
memory_reflection_threshold: 5
memory_reflection_count: 2
memory_time_weight_lambda: 0.8
memory_retrieval_k: 5

# Agent Decision Principles
agent_decision_principles:
  - "Consider your age, interests, social connections, and family situation when deciding on gaming behavior."
  - "Balance between entertainment needs, social interaction, and other activities."
  - "Adapt to gaming restrictions while finding alternative ways to fulfill your entertainment and social needs."

# --- Social Subsystem Configuration ---
subsystem_directory_group: "youth_gaming_limit"
active_subsystems:
  - "YouthBehaviorSystem"
  - "DigitalEntertainmentSystem"

# Configuration specific to each subsystem
subsystem_configs:
  YouthBehaviorSystem:
    required_agent_attributes: [
      "id",
      "basic_info.age",
      "basic_info.education_level",
      "social_attributes.social_style"
    ]
    environment_attributes: ["gaming_restrictions", "alternative_activities", "peer_behavior", "parental_attitudes"]
    decision_attributes:
      - name: "gaming_time_intention"
        description: "<hours per day: 0, 0.5, 1, 1.5, 2, 3, 4+>"
      - name: "compliance_strategy"
        description: "<choose from: 'full_compliance', 'find_loopholes', 'use_parent_account', 'switch_platforms'>"
      - name: "alternative_activity"
        description: "<choose from: 'sports', 'reading', 'socializing', 'studying', 'other_digital', 'none'>"
    
    # Gaming restriction policies by epoch
    gaming_policies:
      "0": {
        "restriction_active": False,
        "max_hours_weekday": 24,
        "max_hours_weekend": 24,
        "allowed_time_slots": "any",
        "age_verification": False,
        "applies_to_age": 18
      }
      "1": {
        "restriction_active": False,
        "max_hours_weekday": 24,
        "max_hours_weekend": 24,
        "allowed_time_slots": "any",
        "age_verification": False,
        "applies_to_age": 18
      }
      "2": {  # Policy introduction
        "restriction_active": True,
        "max_hours_weekday": 1.5,
        "max_hours_weekend": 3,
        "allowed_time_slots": "20:00-21:30",
        "age_verification": True,
        "applies_to_age": 18
      }
      "3": {
        "restriction_active": True,
        "max_hours_weekday": 1,
        "max_hours_weekend": 2,
        "allowed_time_slots": "20:00-21:00",
        "age_verification": True,
        "applies_to_age": 18
      }
      "4": {  # Stricter enforcement
        "restriction_active": True,
        "max_hours_weekday": 0,
        "max_hours_weekend": 1,
        "allowed_time_slots": "20:00-21:00 (Fri-Sun only)",
        "age_verification": True,
        "applies_to_age": 18,
        "real_name_registration": True
      }
      "5": {
        "restriction_active": True,
        "max_hours_weekday": 0,
        "max_hours_weekend": 1,
        "allowed_time_slots": "20:00-21:00 (Fri-Sun only)",
        "age_verification": True,
        "applies_to_age": 18,
        "real_name_registration": True
      }

  DigitalEntertainmentSystem:
    required_agent_attributes: ["id", "basic_info.age"]
    environment_attributes: ["gaming_trends", "platform_availability", "social_gaming_impact"]
    decision_attributes: []
    
    # Entertainment substitution parameters
    gaming_satisfaction_base: 0.8
    alternative_satisfaction: {
      "sports": 0.7,
      "reading": 0.6,
      "socializing": 0.75,
      "studying": 0.3,
      "other_digital": 0.65
    }
    
    # Platform adaptation
    platform_migration_rate: 0.2  # Rate at which users find alternative platforms

# --- Simulation and Evaluation Configuration ---
simulation_name_prefix: "youth_gaming_limit"
num_epochs: 6
start_date: "2024-01-01"
epoch_duration_days: 30
save_decision_prompts: True

# --- Logging Configuration ---
log_level: "INFO" 