# GPLab Configuration File - Pension Policy Reform Experiment

# --- Large Language Model (LLM) and Embedding Model Configuration ---
llm_api_configs:
  - base_url: "http://localhost:3000/v1/"
    api_key: "sk-V395yxePMIyg6eCiNtL2mdlD1LAqA3KKAgj783ElOditm151"
    model: "THUDM/glm-4-9b-chat"
    temperature: 0.7
    top_p: 0.9
    description: "Local GLM-4 for pension policy simulation"
    weight: 1.0

agent_driver_llm_index: [0]
other_llm_index: [0]
embedding_api_index: [0]

# QPS Control Configuration
max_concurrent_requests: 10

use_local_embedding_model: True
local_embedding_model_path: "C://Users//Cromwell//.cache//huggingface//hub//models--sentence-transformers--all-MiniLM-L6-v2//snapshots//e4ce9877abf3edfe10b0d82785e83bdcb973e22e"
embedding_dimension: 384
embedding_device: "cpu"

# --- Social Agent Configuration ---
agent_data_path: "../data/llm_mock_profiles.json"
agent_sample_size: 10
agent_sample_seed: 321
agent_sampling_method: "random"

# Agent Memory System Configuration
memory_reflection_threshold: 5
memory_reflection_count: 2
memory_time_weight_lambda: 0.8
memory_retrieval_k: 5

# Agent Decision Principles
agent_decision_principles:
  - "Consider your age, health status, financial needs, and career satisfaction when making retirement decisions."
  - "Evaluate the trade-offs between continuing to work and enjoying retirement with the new pension benefits."
  - "Think about your long-term financial security and quality of life."

# --- Social Subsystem Configuration ---
subsystem_directory_group: "pension_policy"
active_subsystems:
  - "PensionSystem"
  - "LaborMarketSystem"

# Configuration specific to each subsystem
subsystem_configs:
  PensionSystem:
    required_agent_attributes: [
      "id",
      "basic_info.age",
      "economic_attributes.income_level",
      "economic_attributes.occupation"
    ]
    environment_attributes: ["pension_rates", "retirement_age", "pension_adjustments", "labor_market_conditions"]
    decision_attributes:
      - name: "retirement_decision"
        description: "<choose from: 'continue_working', 'retire_now', 'reduce_hours', 'delay_retirement'>"
      - name: "financial_planning"
        description: "<choose from: 'conservative_saving', 'moderate_investment', 'active_investment', 'spend_more'>"
    
    # Pension policies by epoch
    pension_policies:
      "0": {
        "base_pension_amount": 2000,
        "pension_growth_rate": 0.03,
        "retirement_age": 60,
        "early_retirement_penalty": 0.05,
        "contribution_rate_employee": 0.08,
        "contribution_rate_employer": 0.12,
        "min_contribution_years": 15,
        "fund_annual_return_rate": 0.05
      }
      "1": {
        "base_pension_amount": 2000,
        "pension_growth_rate": 0.03,
        "retirement_age": 60,
        "early_retirement_penalty": 0.05,
        "contribution_rate_employee": 0.08,
        "contribution_rate_employer": 0.12,
        "min_contribution_years": 15,
        "fund_annual_return_rate": 0.05
      }
      "2": {  # Policy reform
        "base_pension_amount": 2500,
        "pension_growth_rate": 0.05,
        "retirement_age": 60,
        "early_retirement_penalty": 0.03,
        "delayed_retirement_bonus": 0.05,
        "contribution_rate_employee": 0.08,
        "contribution_rate_employer": 0.12,
        "min_contribution_years": 15,
        "fund_annual_return_rate": 0.05
      }
      "3": {
        "base_pension_amount": 2800,
        "pension_growth_rate": 0.05,
        "retirement_age": 60,
        "early_retirement_penalty": 0.03,
        "delayed_retirement_bonus": 0.08,
        "contribution_rate_employee": 0.08,
        "contribution_rate_employer": 0.12,
        "min_contribution_years": 15,
        "fund_annual_return_rate": 0.05
      }
      "4": {
        "base_pension_amount": 3000,
        "pension_growth_rate": 0.06,
        "retirement_age": 60,
        "early_retirement_penalty": 0.02,
        "delayed_retirement_bonus": 0.1,
        "contribution_rate_employee": 0.08,
        "contribution_rate_employer": 0.12,
        "min_contribution_years": 15,
        "fund_annual_return_rate": 0.05
      }
      "5": {
        "base_pension_amount": 3000,
        "pension_growth_rate": 0.06,
        "retirement_age": 60,
        "early_retirement_penalty": 0.02,
        "delayed_retirement_bonus": 0.1,
        "contribution_rate_employee": 0.08,
        "contribution_rate_employer": 0.12,
        "min_contribution_years": 15,
        "fund_annual_return_rate": 0.05
      }

  LaborMarketSystem:
    required_agent_attributes: ["id", "basic_info.age"]
    environment_attributes: ["job_opportunities", "wage_levels", "skill_demands"]
    decision_attributes: []
    
    # Labor market parameters
    senior_worker_productivity: 0.85
    experience_premium: 0.2
    job_availability_by_age: {
      "50-55": 0.9,
      "55-60": 0.7,
      "60-65": 0.4,
      "65+": 0.2
    }

# --- Simulation and Evaluation Configuration ---
simulation_name_prefix: "pension_policy"
num_epochs: 6
start_date: "2024-01-01"
epoch_duration_days: 30
save_decision_prompts: True

# --- Logging Configuration ---
log_level: "INFO"