# GPLab Configuration File - Carbon Credit Transport Policy Experiment

# --- Large Language Model (LLM) and Embedding Model Configuration ---
llm_api_configs:
  - base_url: "http://localhost:3000/v1/"
    api_key: "sk-V395yxePMIyg6eCiNtL2mdlD1LAqA3KKAgj783ElOditm151"
    model: "THUDM/glm-4-9b-chat"
    temperature: 0.7
    top_p: 0.9
    description: "Local GLM-4 for carbon transport simulation"
    weight: 1.0

agent_driver_llm_index: [0]
other_llm_index: [0]
embedding_api_index: [0]

# QPS Control Configuration
max_concurrent_requests: 10

use_local_embedding_model: True
local_embedding_model_path: "C://Users//Cromwell//.cache//huggingface//hub//models--sentence-transformers--all-MiniLM-L6-v2//snapshots//e4ce9877abf3edfe10b0d82785e83bdcb973e22e"
embedding_dimension: 384
embedding_device: "cpu"

# --- Social Agent Configuration ---
agent_data_path: "../data/llm_mock_profiles.json"
agent_sample_size: 100
agent_sample_seed: 135
agent_sampling_method: "random"

# Agent Memory System Configuration
memory_reflection_threshold: 5
memory_reflection_count: 2
memory_time_weight_lambda: 0.8
memory_retrieval_k: 5

# Agent Decision Principles
agent_decision_principles:
  - "Consider your daily commute needs, environmental values, and carbon credit balance when choosing transportation."
  - "Evaluate the trade-offs between convenience, cost, and environmental impact."
  - "Adapt your travel behavior based on carbon credit availability and restrictions."

# --- Social Subsystem Configuration ---
subsystem_directory_group: "carbon_credit_transport"
active_subsystems:
  - "TransportChoiceSystem"
  - "CarbonTradingSystem"

# Configuration specific to each subsystem
subsystem_configs:
  TransportChoiceSystem:
    required_agent_attributes: [
      "id",
      "basic_info.age",
      "basic_info.residence_type",
      "economic_attributes.income_level"
    ]
    environment_attributes: ["transport_options", "carbon_prices", "credit_balance", "public_transit_quality"]
    decision_attributes:
      - name: "primary_transport_mode"
        description: "<choose from: 'private_car', 'public_transit', 'bicycle', 'walk', 'mixed'>"
      - name: "carbon_credit_strategy"
        description: "<choose from: 'conserve_credits', 'buy_credits', 'change_behavior', 'ignore_system'>"
      - name: "trip_frequency"
        description: "<daily trips: 0-2 (low), 3-4 (medium), 5+ (high)>"
    
    # Carbon credit policies by epoch
    carbon_policies:
      "0": {
        "system_active": False,
        "monthly_credit_allocation": 0,
        "credit_price": 0,
        "car_credits_per_km": 0
      }
      "1": {
        "system_active": False,
        "monthly_credit_allocation": 0,
        "credit_price": 0,
        "car_credits_per_km": 0
      }
      "2": {  # System introduction
        "system_active": True,
        "monthly_credit_allocation": 100,
        "credit_price": 1.0,
        "car_credits_per_km": 0.5,
        "bus_credits_per_km": 0.1,
        "bike_credits_per_km": -0.1,  # Earn credits
        "walk_credits_per_km": -0.2
      }
      "3": {
        "system_active": True,
        "monthly_credit_allocation": 80,
        "credit_price": 1.5,
        "car_credits_per_km": 0.8,
        "bus_credits_per_km": 0.1,
        "bike_credits_per_km": -0.2,
        "walk_credits_per_km": -0.3
      }
      "4": {  # Stricter limits
        "system_active": True,
        "monthly_credit_allocation": 60,
        "credit_price": 2.0,
        "car_credits_per_km": 1.0,
        "bus_credits_per_km": 0.05,
        "bike_credits_per_km": -0.3,
        "walk_credits_per_km": -0.4,
        "credit_trading_allowed": True
      }
      "5": {
        "system_active": True,
        "monthly_credit_allocation": 60,
        "credit_price": 2.5,
        "car_credits_per_km": 1.2,
        "bus_credits_per_km": 0.05,
        "bike_credits_per_km": -0.3,
        "walk_credits_per_km": -0.4,
        "credit_trading_allowed": True
      }

  CarbonTradingSystem:
    required_agent_attributes: ["id"]
    environment_attributes: ["market_prices", "trading_volume", "emission_statistics"]
    decision_attributes: []
    
    # Transport emission parameters
    transport_emissions: {
      "private_car": 120,  # g CO2/km
      "public_transit": 30,
      "bicycle": 0,
      "walk": 0
    }
    
    # Market parameters
    initial_credit_supply: 10000
    price_elasticity: 0.3

# --- Simulation and Evaluation Configuration ---
simulation_name_prefix: "carbon_credit_transport"
num_epochs: 6
start_date: "2024-01-01"
epoch_duration_days: 30
save_decision_prompts: True

# --- Logging Configuration ---
log_level: "INFO" 