# GPLab Configuration File - SME Tax Reduction Policy Experiment

# --- Large Language Model (LLM) and Embedding Model Configuration ---
llm_api_configs:
  - base_url: "http://localhost:3000/v1/"
    api_key: "sk-V395yxePMIyg6eCiNtL2mdlD1LAqA3KKAgj783ElOditm151"
    model: "THUDM/glm-4-9b-chat"
    temperature: 0.7
    top_p: 0.9
    description: "Local GLM-4 for SME tax policy simulation"
    weight: 1.0

agent_driver_llm_index: [0]
other_llm_index: [0]
embedding_api_index: [0]

# QPS Control Configuration
max_concurrent_requests: 10

use_local_embedding_model: True
local_embedding_model_path: "C://Users//Cromwell//.cache//huggingface//hub//models--sentence-transformers--all-MiniLM-L6-v2//snapshots//e4ce9877abf3edfe10b0d82785e83bdcb973e22e"
embedding_dimension: 384
embedding_device: "cpu"

# --- Social Agent Configuration ---
agent_data_path: "../data/llm_mock_profiles.json"
agent_sample_size: 100
agent_sample_seed: 987
agent_sampling_method: "random"

# Agent Memory System Configuration
memory_reflection_threshold: 5
memory_reflection_count: 2
memory_time_weight_lambda: 0.8
memory_retrieval_k: 5

# Agent Decision Principles
agent_decision_principles:
  - "Consider your entrepreneurial spirit, risk tolerance, and financial resources when making business decisions."
  - "Evaluate the benefits of tax reductions against the challenges of starting and running a business."
  - "Think about market opportunities, competition, and your skills when deciding on entrepreneurship."

# --- Social Subsystem Configuration ---
subsystem_directory_group: "sme_tax_reduction"
active_subsystems:
  - "EntrepreneurshipSystem"
  - "EmploymentSystem"

# Configuration specific to each subsystem
subsystem_configs:
  EntrepreneurshipSystem:
    required_agent_attributes: [
      "id",
      "basic_info.age",
      "basic_info.education_level",
      "economic_attributes.income_level",
      "psychological_attributes.core_values"
    ]
    environment_attributes: ["tax_policies", "market_conditions", "startup_costs", "business_opportunities"]
    decision_attributes:
      - name: "entrepreneurship_intention"
        description: "<a value between 0.0 and 1.0 indicating your intention to start a business>"
      - name: "business_type"
        description: "<choose from: 'tech_startup', 'retail', 'service', 'manufacturing', 'none'>"
      - name: "hiring_intention"
        description: "<number of employees you plan to hire: 0, 1-5, 6-20, 21-50>"
    
    # SME tax policies by epoch
    tax_policies:
      "0": {
        "sme_tax_rate": 0.25,
        "startup_tax_exemption_years": 0,
        "r_and_d_tax_credit": 0.1,
        "employment_subsidy_per_person": 0
      }
      "1": {
        "sme_tax_rate": 0.25,
        "startup_tax_exemption_years": 0,
        "r_and_d_tax_credit": 0.1,
        "employment_subsidy_per_person": 0
      }
      "2": {  # Policy introduction
        "sme_tax_rate": 0.20,
        "startup_tax_exemption_years": 1,
        "r_and_d_tax_credit": 0.15,
        "employment_subsidy_per_person": 1000,
        "simplified_registration": True
      }
      "3": {
        "sme_tax_rate": 0.15,
        "startup_tax_exemption_years": 2,
        "r_and_d_tax_credit": 0.20,
        "employment_subsidy_per_person": 2000,
        "simplified_registration": True
      }
      "4": {  # Enhanced support
        "sme_tax_rate": 0.10,
        "startup_tax_exemption_years": 3,
        "r_and_d_tax_credit": 0.25,
        "employment_subsidy_per_person": 3000,
        "simplified_registration": True,
        "free_business_consulting": True
      }
      "5": {
        "sme_tax_rate": 0.10,
        "startup_tax_exemption_years": 3,
        "r_and_d_tax_credit": 0.25,
        "employment_subsidy_per_person": 3000,
        "simplified_registration": True,
        "free_business_consulting": True
      }

  EmploymentSystem:
    required_agent_attributes: ["id", "economic_attributes.occupation"]
    environment_attributes: ["job_market", "wage_levels", "employment_opportunities"]
    decision_attributes: []
    
    # Employment model parameters
    base_unemployment_rate: 0.05
    job_creation_multiplier: 2.5  # Each new business creates 2.5 jobs on average
    wage_growth_from_competition: 0.02

# --- Simulation and Evaluation Configuration ---
simulation_name_prefix: "sme_tax_reduction"
num_epochs: 6
start_date: "2024-01-01"
epoch_duration_days: 30
save_decision_prompts: True

# --- Logging Configuration ---
log_level: "INFO" 