# GPLab Configuration File - Birth Subsidy Policy Experiment

# --- Large Language Model (LLM) and Embedding Model Configuration ---
llm_api_configs:
  - base_url: "http://localhost:3000/v1/"
    api_key: "sk-V395yxePMIyg6eCiNtL2mdlD1LAqA3KKAgj783ElOditm151"
    model: "THUDM/glm-4-9b-chat"
    temperature: 0.7
    top_p: 0.9
    description: "Local GLM-4 for birth subsidy simulation"
    weight: 1.0

agent_driver_llm_index: [0]
other_llm_index: [0]
embedding_api_index: [0]

# QPS Control Configuration
max_concurrent_requests: 10

use_local_embedding_model: True
local_embedding_model_path: "C://Users//Cromwell//.cache//huggingface//hub//models--sentence-transformers--all-MiniLM-L6-v2//snapshots//e4ce9877abf3edfe10b0d82785e83bdcb973e22e"
embedding_dimension: 384
embedding_device: "cpu"

# --- Social Agent Configuration ---
agent_data_path: "../data/llm_mock_profiles.json"
agent_sample_size: 100
agent_sample_seed: 789
agent_sampling_method: "random"

# Agent Memory System Configuration
memory_reflection_threshold: 5
memory_reflection_count: 2
memory_time_weight_lambda: 0.8
memory_retrieval_k: 5

# Agent Decision Principles
agent_decision_principles:
  - "Consider your age, marital status, financial situation, and career plans when making family planning decisions."
  - "Evaluate the long-term costs and benefits of having children, including government subsidies."
  - "Balance personal desires, family pressure, and practical constraints in your decision."

# --- Social Subsystem Configuration ---
subsystem_directory_group: "birth_subsidy"
active_subsystems:
  - "DemographicSystem"
  - "FamilyPlanningSystem"

# Configuration specific to each subsystem
subsystem_configs:
  DemographicSystem:
    required_agent_attributes: [
      "id",
      "basic_info.age",
      "basic_info.gender",
      "basic_info.marital_status",
      "economic_attributes.income_level"
    ]
    environment_attributes: ["birth_policies", "subsidy_amounts", "childcare_costs", "demographic_trends"]
    decision_attributes:
      - name: "fertility_intention"
        description: "<a value between 0.0 and 1.0 indicating your intention to have a child in the near future>"
      - name: "ideal_number_of_children"
        description: "<choose from: 0, 1, 2, 3 - your ideal number of children>"
    
    # Birth subsidy policies by epoch
    birth_policies:
      "0": {
        "first_child_subsidy": 0,
        "second_child_subsidy": 0,
        "third_child_subsidy": 0,
        "monthly_childcare_allowance": 0,
        "maternity_leave_days": 98
      }
      "1": {
        "first_child_subsidy": 0,
        "second_child_subsidy": 0,
        "third_child_subsidy": 0,
        "monthly_childcare_allowance": 0,
        "maternity_leave_days": 98
      }
      "2": {  # Policy introduction
        "first_child_subsidy": 5000,
        "second_child_subsidy": 10000,
        "third_child_subsidy": 20000,
        "monthly_childcare_allowance": 500,
        "maternity_leave_days": 128,
        "paternity_leave_days": 15
      }
      "3": {
        "first_child_subsidy": 5000,
        "second_child_subsidy": 10000,
        "third_child_subsidy": 20000,
        "monthly_childcare_allowance": 500,
        "maternity_leave_days": 128,
        "paternity_leave_days": 15
      }
      "4": {  # Enhanced subsidies
        "first_child_subsidy": 10000,
        "second_child_subsidy": 20000,
        "third_child_subsidy": 50000,
        "monthly_childcare_allowance": 1000,
        "maternity_leave_days": 158,
        "paternity_leave_days": 30,
        "free_kindergarten": True
      }
      "5": {
        "first_child_subsidy": 10000,
        "second_child_subsidy": 20000,
        "third_child_subsidy": 50000,
        "monthly_childcare_allowance": 1000,
        "maternity_leave_days": 158,
        "paternity_leave_days": 30,
        "free_kindergarten": True
      }

  FamilyPlanningSystem:
    required_agent_attributes: ["id", "basic_info.age", "basic_info.gender"]
    environment_attributes: ["social_norms", "peer_fertility", "work_life_balance"]
    decision_attributes: []
    
    # Fertility model parameters
    peak_fertility_age: 28
    fertility_age_range: [20, 45]
    base_fertility_rate: 0.05  # Monthly probability
    
    # Cost estimates
    child_raising_cost_annual: 50000
    education_cost_total: 500000

# --- Simulation and Evaluation Configuration ---
simulation_name_prefix: "birth_subsidy"
num_epochs: 6
start_date: "2024-01-01"
epoch_duration_days: 30
save_decision_prompts: True

# --- Logging Configuration ---
log_level: "INFO" 